category, store jpa 적용
f-lab-edu/bbaemin pull request #21
Opened 2023-02-16 05:04 UTC by CHANEE-personal

1. Category CRUD jpa
2. Store CRUD jpa

2023-02-18 11:54 UTC, yeonkyungJoo requested changes
Store 부분은 Category 관련 클래스에 추가한 코멘트와 동일해서 따로 추가하지 않았습니다. 확인 부탁드립니다.

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/controller/CategoryController.java
> +    public ApiResult<CategoryDto> updateCategory(@PathVariable Long categoryId, @RequestBody CategoryEntity categoryEntity) {
Controller에서 JPA Entity를 사용하는 게 좋은 방법일까요?

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
JPA Entity가 왜 public/protected no-args constructor를 꼭 필요로 하는지 짚고 넘어가는 게 좋을 거 같아요!

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    @NotNull(message = "코드값 입력은 필수입니다.")
Controller에서 request를 받기 위한 클래스로 사용해서 위와 같은 Validation 설정을 넣으신 거 같은데요!
저는 Validation 체크를 위해 request 객체를 따로 생성하는 편입니다. 같이 얘기해보는 게 좋을 것 같아요!!

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    private Boolean useYn;
useYn은 어떤 컬럼인가요? boolean이 아닌 Boolean을 사용하신 이유가 있으신가요?

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    @Column(name = "code")
필수값이면 nullable = false 설정을 해주시는 건 어떨까요? 유일해야 하는 값이면 unique 설정도요!
@Column 속성에 어떤 것들이 있는지 확인해보는 것도 좋을 거 같아요!

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    @Builder.Default
이건 왜 하는 건가요?

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    private List<StoreEntity> storeList = new ArrayList<>();
Category와 Store가 어떤 연관이 있는 건가요?

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/service/CategoryService.java
> +        return categoryRepository.findById(categoryId).orElseThrow();
예외를 명시해서 던져주는 게 좋을 것 같아요!

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/service/CategoryService.java
> +        categoryRepository.findById(categoryId);
delete 해줘야 하는 거 아닌가요?

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/test/java/org/bbaemin/category/service/CategoryServiceTest.java
>      @EventListener(ApplicationReadyEvent.class)
@BeforeEach면 각 테스트마다 실행될텐데 @EventListener를 추가하신 이유가 무엇인가요?

2023-02-18 11:54 UTC, yeonkyungJoo commented on bbaemin-api/src/test/java/org/bbaemin/store/service/StoreServiceTest.java
> +    @Mock private StoreRepository mockStoreRepository;
어노테이션과 필드 선언을 한 줄에 할 지, 두 줄에 나눠서 할 지
이것도 맞추는 게 좋을 거 같아요.

2023-02-18 12:15 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +@DynamicUpdate
DynamicUpdate가 성능 상 오버헤드가 있는 것으로 알고 있는데요. update를 어떻게 할 지 의논해봐요!!

2023-02-18 13:22 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    private List<StoreEntity> storeList = new ArrayList<>();
Store 같은경우에도 매장이나 편의점등등해서 여러가지 카테고리가 존재하다고 생각해서 설정해봤습니다!

2023-02-18 13:22 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/service/CategoryService.java
> +        categoryRepository.findById(categoryId);
엇! 이 부분은 실수했네요! 수정해서 다시 올려놓도록 하겠습니다.

2023-02-18 13:25 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    private Boolean useYn;
잘못 사용했네요. 이 부분 수정해서 다시 올려놓도록 하겠습니다!

2023-02-18 13:29 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/domain/CategoryEntity.java
> +    @Builder.Default
@Builder 어노테이션을 사용하다보면 List를 초기화했음에도 불구하고 NullPointerException 발생을 하더라고요.
해결책을 찾아보니 위와 같은 방법이 있어서 설정을 해뒀습니다.

2023-02-24 00:32 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/store/domain/Store.java
> +    @NotBlank(message = "매장명 입력은 필수입니다.")
이 코드는 Controller의 CreateStoreRequest, UpdateStoreRequest에 있어야 Validated 체크가 되지 않을까요?

2023-02-25 06:39 UTC, yeonkyungJoo approved these changes

2023-02-25 06:40 UTC, merged