Item jpa 적용
f-lab-edu/bbaemin pull request #24
Opened 2023-02-18 10:38 UTC by CHANEE-personal

1. item jpa 적용
2. item Controller APi Result 적용

2023-02-19 05:40 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/item/domain/ItemDTO.java
> +public class ItemDTO {
nit: `DTO`보다는 `Dto`가 더 맞지 않을까 하는 생각이 ... :-)

2023-02-19 05:41 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/item/domain/ItemEntity.java
> +import lombok.*;
`*`를 풀어서 넣어주세요.

2023-02-19 05:42 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/item/repository/ItemRepository.java
> +    @Query("select i from ItemEntity i join fetch i.itemCategory join fetch i.itemStore where i.itemId = :itemId")
오 ... 위에도 비슷한 코드가 있는데, 이렇게 하면 안될 것 같은 느낌같은 느낌이 들어요... 이러면, JPA를 쓰는 이득이 거의 없지 않을까 싶은 생각이 드네요.

2023-02-19 05:47 UTC, f-lab-lyan requested changes

2023-02-19 05:47 UTC, f-lab-lyan commented on bbaemin-api/src/test/java/org/bbaemin/item/service/ItemServiceTest.java
> +@TestConstructor(autowireMode = ALL)
테스트 코드가, 유닛 테스트와 인티그레이션 테스트가 합쳐져 있는데, 일반적으로 분리하는 게 더 좋은 습관 같습니다. 유닛 테스트를 돌리는데 굳이 스프링 환경 설정을 다 읽을 필요는 없을 것 같네요.

2023-02-19 05:47 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/item/domain/ItemEntity.java
> +    public static ItemDTO toDto(ItemEntity entity) {
이 메소드는 static 메소드일 필요가 없어 보이는데요. 그냥 자기 자신을 가지고 toDto하면 되지 않을까요?

2023-02-23 15:17 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/item/domain/ItemDTO.java
> +public class ItemDTO {
수정 완료했습니다

2023-02-23 15:18 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/item/domain/ItemEntity.java
> +import lombok.*;
수정 완료했습니다.

2023-02-23 15:19 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/item/repository/ItemRepository.java
> +    @Query("select i from ItemEntity i join fetch i.itemCategory join fetch i.itemStore where i.itemId = :itemId")
@EntityGraph 사용????

2023-02-23 15:19 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/item/service/ItemServiceTest.java
> +@TestConstructor(autowireMode = ALL)
수정 완료했습니다.

2023-02-23 15:19 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/item/domain/ItemEntity.java
> +    public static ItemDTO toDto(ItemEntity entity) {
삭제 후 Response로 변환해서 보내주기로 했습니다!

2023-02-24 01:07 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/item/controller/ItemController.java
> +    public ApiResult<ItemResponse> createItem(@Validated @RequestBody Item item) {
여기서는 엔티티를 사용하셨네요. 확인 부탁드립니다.

2023-02-25 00:33 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/item/controller/ItemController.java
> +    public ApiResult<ItemResponse> createItem(@Validated @RequestBody Item item) {
수정 완료

2023-02-25 07:11 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/item/service/ItemService.java
> +    @Transactional(readOnly = true)
이 부분은 왜 필요한지 나중에 한 번 얘기해보도록 하죠. :-)

2023-02-25 07:11 UTC, f-lab-lyan approved these changes
자잘한 부분에서 손을 좀 봐야할 것 같지만, 일단은 괜찮은 것 같습니다.

2023-02-25 07:14 UTC, merged