User JPA 적용, BindException 처리
f-lab-edu/bbaemin pull request #26
Opened 2023-02-18 17:54 UTC by yeonkyungJoo

1. JPA 적용
2. ApiResult 적용 및 Controller 테스트 작성
3. Validation 체크 및 ControllerExceptionAdvice 생성

2023-02-19 05:32 UTC, CHANEE-personal requested changes

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +        return ApiResult.ok(new UserResponse(user));
ApiResult에 대해서 생각을 해봤는데 
Get, Put에 대해서는 success(200)을 사용하고
Post 등록에 관해서는 created(201),
Delete 삭제에 관해서는 nocontent(204)에 대해서 추가하는거 어떻게 생각하실까요???

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/config/advice/ControllerExceptionAdvice.java
> +    @ExceptionHandler(BindException.class)
이 부분에 대해서
MethodArgumentNotValidException는 RequestBody에 대한 값을 받아올 때 사용하고
BindException은 ModelAttribute에 대한 값을 받아올 때 사용 하는 걸로 알고 있는데
어떻게 생각하실까요???

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/config/advice/ControllerExceptionAdvice.java
> +@RestControllerAdvice
이 부분에 대해서 basePackage 설정하는 부분이 있던데 추후에 cart, user, order, item 등을 api package로 따로 빼서
org.bbaemin.api를 basePackage로 주는거에 대해서 어떻게 생각하실까요????

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +    public ApiResult<UserResponse> join(@Validated @RequestBody JoinRequest joinRequest, BindingResult bindingResult) {
이 부분에 대해서 저는 @Valid로 작업을 했고 연경님은 @Validated로 작업을 해주셨는데
어떻게 통일을 할지에 대해서 의논이 필요해보입니다!

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/user/service/UserServiceTest.java
> +    @Autowired
junit5부터는 생성자 주입방식도 활용할 수 있다고 알고 있는데
@Testconstructor(autowireMode = TestConstructor.AutowireMode.ALL)에 대해서도
같이 공부하면 좋을 거 같습니다!

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +    public ApiResult<List<UserResponse>> listUser() {
추후에 리스트 검색 같은 기능에 대해서는 어떻게 구현할지에 대한 의논이 필요할 거 같습니다!
저는 우선 이렇게 생각해봤습니다.
1. querydsl BooleanExpression을 활용한 검색??? -> 이럴 경우 querydsl 설정 필요
2. jpa pageable, containing을 활용한 검색???

2023-02-19 05:32 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/user/service/UserServiceTest.java
> +    @PostConstruct
이걸 보니까 저번에 @f-lab-lyan 멘토님이 권장하지 않는 방법이라고 적어주셨는데 같이 공부해보면 좋을 거 같습니다!
* 장점
1. bean이 초기화됨과 동시에 의존성을 확인할 수 있다는 장점
2. bean lifeCycle에서 오직 한 번만 수행된다는 것이 보장된다는 장점
* 단점
1. @Transactional과 관련된 단점
* userService.save 호출(@Transactional 선언) -> userService -> userRepository = 동일한 트랜잭션 -> context init이 이루어진 상태 -> 정상 작동
* userRepository.save 호출(@Transactional이 선언되어 있지 않은 경우) -> userRepository = @Transactional이 적용되었다는 보장 X -> 정상 작동 X

다른 의견 있으시면 답변 부탁드릴게요! :)

2023-02-19 05:53 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +        }
이건 괜찮아 보이는데, 너무 친절한 느낌이군요. :-) (나쁘다는 의미는 아닙니다.)

2023-02-21 00:34 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +    public ApiResult<UserResponse> join(@Validated @RequestBody JoinRequest joinRequest, BindingResult bindingResult) {
Validated로 통일 완료

2023-02-21 00:34 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +    public ApiResult<List<UserResponse>> listUser() {
Issue로 등록했습니다.

2023-02-21 10:46 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/config/advice/ControllerExceptionAdvice.java
> +    @ExceptionHandler(BindException.class)
아 넵! MethodArgumentNotValidException을 사용해서 바로 처리하는 게 좋을 것 같아요! 수정했습니다.

2023-02-21 10:47 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/config/advice/ControllerExceptionAdvice.java
> +@RestControllerAdvice
@CHANEE-personal 네! 이거는 나중에 대충 다 만들고 나서 한번에 정리하시죠!

2023-02-21 11:45 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/user/controller/UserController.java
> +        return ApiResult.ok(new UserResponse(user));
@CHANEE-personal 우선 ResultCode.CREATED 추가했습니다. 확인 부탁드려요!

2023-02-21 12:00 UTC, yeonkyungJoo commented on bbaemin-api/src/test/java/org/bbaemin/user/service/UserServiceTest.java
> +    @Autowired
네 감사합니다.

2023-02-21 12:05 UTC, yeonkyungJoo commented on bbaemin-api/src/test/java/org/bbaemin/user/service/UserServiceTest.java
> +    @PostConstruct
@CHANEE-personal 트랜잭션 관련된 단점이 이해가 잘 안 가요!
일단 저는 그 코드에서는 PostConstruct를 사용하지 않는 것이 맞다고 판단했었는데, 이 코드에서도 좋은 방법이 아닌지는 판단이 잘 서지 않아서요! 다시 확인해보겠습니다!!

2023-02-21 13:03 UTC, CHANEE-personal approved these changes

2023-02-21 13:03 UTC, merged