Review API 추가
f-lab-edu/bbaemin pull request #27
Opened 2023-02-19 07:14 UTC by yeonkyungJoo

2023-02-25 06:23 UTC, CHANEE-personal requested changes

2023-02-25 06:23 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/review/controller/ReviewController.java
> +    // TODO - CHECK : /api/v1/reviews vs /api/v1/orders/{orderId}/reviews
주문 리뷰뿐만 아니라 상품리뷰까지 추가해보시는건 어떨까요???

2023-02-25 15:15 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/review/controller/ReviewController.java
> +    // TODO - CHECK : /api/v1/reviews vs /api/v1/orders/{orderId}/reviews
상품 리뷰로 수정했습니다.

2023-02-26 11:49 UTC, f-lab-lyan approved these changes
특별히 손 볼 곳은 없어보입니다. (뭔가 .. 어떻게 하면 제가 별 코멘트 없이 리뷰를 승인해줄껀지 아시게 된 것 같은 느낌이지만... :-))

2023-03-01 07:20 UTC, CHANEE-personal approved these changes

2023-03-01 07:21 UTC, merged