Order - JPA 적용
f-lab-edu/bbaemin pull request #28
Opened 2023-02-19 10:10 UTC by yeonkyungJoo

2023-02-25 05:59 UTC, CHANEE-personal requested changes

2023-02-25 05:59 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/controller/OrderController.java
> +    public ApiResult<OrderResponse> order(@RequestParam Long userId, @RequestBody CreateOrderRequest createOrderRequest) {
@Validated 빠진 거 같습니다.

2023-02-25 05:59 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private Long userId;            // orderer
이거에 대해서 궁금한게 있는데요!
1. 보통 user entity와 연관 관계 설정해서 작업하는 방법
2. userId -> insertable, updatable -> false로 설정해두고 user entity와 연관관계 설정해서 작업을 하는 방법

두가지 다 활용하는편일까요????

2023-02-25 05:59 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private OrderStatus status;          // 주문완료, 주문취소 / 배달중, 배달완료, 배달취소
Enum을 이렇게 선언하게 되면 column에 들어갈 때 숫자로 들어가지 않을까요???
@Enumerated(EnumType.STRING)로 선언해서 명확하게 들어가게끔 수정하는게 좋을 거 같습니다!

2023-02-25 05:59 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private String paymentMethod;   // 결제 수단
결제 수단도 여러가지가 있다보니 enum을 활용하는거 어떻게 생각하실까요???

2023-02-25 05:59 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private String messageToRider;  // 라이더님께
message나 desription 같은경우에는 아무래도 더 길어질수도 있다보니 @Lob annotation 추가하는거 어떻게 생각하실까요???

2023-02-25 06:18 UTC, CHANEE-personal requested changes

2023-02-25 06:18 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/order/controller/OrderControllerTest.java
> +    @Test
보통 method명에서 추측을 할 수 있겠지만 test case에 @DisplayName 추가해서 작업하는건 어떻게 생각하실까요???

2023-02-25 09:34 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/order/controller/OrderController.java
> +    public ApiResult<OrderResponse> order(@RequestParam Long userId, @RequestBody CreateOrderRequest createOrderRequest) {
추가했습니다.

2023-02-25 11:23 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private OrderStatus status;          // 주문완료, 주문취소 / 배달중, 배달완료, 배달취소
수정했습니다.

2023-02-25 11:23 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private String paymentMethod;   // 결제 수단
수정했습니다.

2023-02-25 11:24 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
>      private String messageToRider;  // 라이더님께
수정했습니다.

2023-02-25 11:24 UTC, yeonkyungJoo commented on bbaemin-api/src/test/java/org/bbaemin/order/controller/OrderControllerTest.java
> +    @Test
네 좋아요. 앞으로 그렇게 하겠습니다.

2023-02-26 11:45 UTC, CHANEE-personal requested changes

2023-02-26 11:45 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/service/CouponService.java
> +
Coupon에 만료일자 관련 column 추가해주신거 같은데 만료일자에 대한 validation check도 있어야할 거 같습니다!

2023-02-26 11:45 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/order/vo/Order.java
> +
orderAmount(주문 금액(원가)), orderSaleAmount(주문 할인 금액)으로 나눠서 표현하는건 어떨까요???
order에도 어떤 coupon을 사용해서 결제를 했는지에 대한 정보가 있으면 좋을 거 같습니다.

2023-02-26 11:45 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/order/service/CouponServiceTest.java
> +class CouponServiceTest {
만료일자에 대한 test case도 있으면 좋을 거 같습니다!

2023-02-26 12:04 UTC, f-lab-lyan commented on bbaemin-api/src/test/java/org/bbaemin/order/service/OrderServiceTest.java
> +        fail();
??

2023-02-26 12:07 UTC, f-lab-lyan commented on bbaemin-api/src/test/java/org/bbaemin/order/controller/OrderControllerTest.java
> +class OrderControllerTest {
Controller 테스트에 WebMvcTest를 적용하기로 하신 건가요? cc/ @CHANEE-personal

2023-02-26 12:13 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/order/service/CouponService.java
> +            userCoupon.setUsedAt(LocalDateTime.now());
쿠폰을 썼으면, 저장을 해야하지 않을까요?

2023-02-26 12:20 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/order/controller/request/CreateOrderRequest.java
> +//    private boolean reserve;                      // 바로 배달 vs 예약 배달
오 .. 뭔가 정성이 느껴지는 띄어쓰기 군요!!! :-)

2023-02-26 12:25 UTC, f-lab-lyan approved these changes
뭔가 서비스가 점점 복잡해 지고 있는 것 같아서, 어떤 기능이 있는지 정확히 정리를 해야할 것 같은 느낌이 듭니다만, 복잡해 지는 것 자체는 좋은 것 같습니다. 어떻게 정리할지에 대해서도 고민해 보시면 좋을 것 같습니다.

2023-02-26 12:47 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/order/controller/OrderControllerTest.java
> +class OrderControllerTest {
@f-lab-lyan 아 이 부분에 대해서는 연경님이랑 다시 한 번 얘기를 나눠보겠습니다

2023-03-01 05:42 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/order/service/CouponService.java
> +
추가했습니다.

2023-03-01 07:21 UTC, CHANEE-personal approved these changes

2023-03-01 07:21 UTC, merged