Cart - JPA 적용
f-lab-edu/bbaemin pull request #29
Opened 2023-02-19 10:16 UTC by yeonkyungJoo

2023-02-25 06:15 UTC, CHANEE-personal requested changes

2023-02-25 06:15 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/cart/controller/CartController.java
> +    public ApiResult<CartResponse> addItem(@PathVariable Long userId, @RequestBody CreateCartItemRequest createCartItemRequest) {
@Validated 빠진 거 같습니다.
혹시 Request에 딱히 check할 validation이 없어서 추가 안하신걸까요???

2023-02-25 06:15 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/cart/controller/CartController.java
>          cartItemService.addItem(userId, createCartItemRequest.getItemId());
아 그리고 비회원 장바구니에 대해서 생각을 해봤는데 뭐 예를 들어 16자리 랜덤 문자를 활용해서 cart_token을 하나 담아주는건 어떻게 생각하실까요??? 

ex) cart flow
 비회원 카트(cart_token) 저장 -> 회원 가입 -> 가지고 있던 cart_token으로 조회해서 user_id update

2023-02-25 06:15 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/cart/vo/CartItem.java
>      private Long itemId;
order쪽 review와 동일합니다.

2023-02-25 06:29 UTC, CHANEE-personal requested changes

2023-02-25 06:29 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/cart/controller/CartController.java
>      private final DeliveryFeeService deliveryFeeService;
이건 아직 안 올려주신거 같은데 작업중이실까요???

2023-02-25 08:49 UTC, yeonkyungJoo commented on bbaemin-api/src/main/java/org/bbaemin/cart/controller/CartController.java
> +    public ApiResult<CartResponse> addItem(@PathVariable Long userId, @RequestBody CreateCartItemRequest createCartItemRequest) {
수정했습니다.

2023-02-26 11:45 UTC, CHANEE-personal requested changes

2023-02-26 11:45 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/cart/service/CartItemService.java
> +        });
음... 이 부분에 대해서 생각을 좀 해봤는데 동일한 아이템에 대한 처리를 해주신거 같은데 Exception 처리보다는 동일한 상품에 대해서는 Count를 하나 추가 해주는것이 맞지 않을까요???

2023-02-26 11:45 UTC, CHANEE-personal commented on bbaemin-api/src/test/java/org/bbaemin/cart/controller/CartControllerTest.java
> +    @Test
위 리뷰와 동일합니다!

2023-02-26 11:50 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/cart/controller/CartController.java
>          cartItemService.addItem(userId, createCartItemRequest.getItemId());
괜찮은 것 같습니다. 시나리오 테스트가 필요할 것 같네요.

2023-02-26 11:54 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/cart/repository/CartItemRepository.java
> +    @Modifying
이 어노테이션은 꼭 필요한 것인가요?

2023-02-26 11:57 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/cart/controller/CartController.java
> +    private CartResponse getCartOfUser(Long userId) {
음 ... 이렇게 하면, 코드는 깔끔해지긴 하는데요. 사실은 cardItemList같은 것들은 이미 서비스 내부에서 처리될 때, 한번은 불러오게 되는게 아닐까 싶은데요. 멘토링 시간에 잠깐 얘기해보면, 좋을 것 같습니다.

2023-02-26 12:01 UTC, f-lab-lyan approved these changes

2023-03-01 07:21 UTC, CHANEE-personal approved these changes

2023-03-01 07:24 UTC, merged