category controller CRUD
f-lab-edu/bbaemin pull request #3
Opened 2023-01-21 03:17 UTC by CHANEE-personal

1. category controller CRUD
2. README 작성
3. build gradle 수정

2023-01-21 05:17 UTC, f-lab-lyan requested changes

2023-01-21 05:17 UTC, f-lab-lyan commented on bbaemin-api/build.gradle
> +    implementation "com.h2database:h2"
이 의존성은 지금은 필요없어 보이네요. :-)

2023-01-21 05:17 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +                "}";
이렇게 리턴하면, 클라이언트에서는 이걸 string으로 인식하는지 json으로 인식하는지 확인해서 알려주시겠어요?

2023-01-21 05:17 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +    public Object createCategory() {
Post는 인풋으로 뭔가를 받아야하지 않나요?

2023-01-21 05:57 UTC, CHANEE-personal commented on bbaemin-api/build.gradle
> +    implementation "com.h2database:h2"
넵 삭제하도록 하겠습니다!

2023-01-21 05:58 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +                "}";
넵 확인해서 코멘트 남겨놓도록 하겠습니다!

2023-01-21 05:59 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +    public Object createCategory() {
CategoryDTO 하나 작성해서 input으로 보내주도록 하겠습니다!

2023-01-21 08:00 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +                "}";
확인 결과 리턴 결과 클라이언트에서 string으로만 인식하고 있습니다.  json으로 리턴되게끔 수정이 필요할까요???

2023-01-22 03:01 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +                "}";
어떻게 하면, json으로 리턴 되는 것 처럼 보이게 할 수 있을까요? 실제 object를 리턴하지 않고, json처럼 보이게 할 수 있는 방법이 있을까요?

2023-01-22 04:08 UTC, CHANEE-personal commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +                "}";
1. Map이나 List를 활용해서 return하는 방식
2. CategoryDto를 활용해서 return 하는 방식
3. JSONObject를 활용해서 return 하는 방식
위 방식들이 있는걸로 알고 있는데 여쭤보신 의도가 이게 맞는걸까요???

2023-01-23 08:06 UTC, f-lab-lyan commented on bbaemin-api/build.gradle
> +    implementation "com.h2database:h2"
<img width="237" alt="image" src="https://user-images.githubusercontent.com/90605505/213991621-02c6ed3f-2dd5-4791-9227-442e1afe20af.png">

이걸 활용해 보는건 어떨까요? :-)

2023-01-23 08:07 UTC, f-lab-lyan commented on bbaemin-api/src/main/java/org/bbaemin/category/CategoryController.java
> +                "}";
@RequestMapping의 `produces`를 확인해보시면 좋을 것 같습니다.

2023-01-24 13:55 UTC, yeonkyungJoo approved these changes

2023-01-25 01:08 UTC, f-lab-lyan approved these changes

2023-01-25 01:11 UTC, merged